#!/usr/bin/env bash

# create source and select directories to backup with corresponding destination directories
declare -A SOURCE_DIRS
SOURCE_DIRS["$HOME/.config"]="ags btop cava gtk-3.0 nvim hypr kitty Kvantum foot neofetch qt5ct qt6ct rofi swappy swaync tmux wallust waybar wlogout zsh"
SOURCE_DIRS["$HOME/.local"]="scripts"  

# destination of the backup with multiple directories
declare -A DEST_DIRS
BASE_DEST="$HOME/backup/arch-backup" 
DEST_DIRS["$HOME/.config"]="${BASE_DEST}/.config/"
DEST_DIRS["$HOME/.local"]="${BASE_DEST}/.local/"

repo_name="arch-hyprland-dots" 
github_username=$(gh api user --jq '.login') || { echo -e "${RED}Failed to retrieve GitHub username.${NC}"; exit 1; } 

# output colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'  

# create the destination directories if they don't exist
for dest in "${!DEST_DIRS[@]}"; do
    mkdir -p "${DEST_DIRS[$dest]}" || { echo -e "${RED}Failed to create destination directory: ${DEST_DIRS[$dest]}.${NC}"; exit 1; }
done

# cp source dirs to their respective destinations
for SOURCE_DIR in "${!SOURCE_DIRS[@]}"; do
    echo -e "${GREEN}Processing directory: $SOURCE_DIR${NC}"
    
    dirs_to_copy="${SOURCE_DIRS[$SOURCE_DIR]}"
    dest_dir="${DEST_DIRS[$SOURCE_DIR]}"
    
    for dir in $dirs_to_copy; do
        src_path="$SOURCE_DIR/$dir"
        if [ -e "$src_path" ]; then  # Check if the directory or file exists
            rsync -aq --delete --exclude='.git/' "$src_path/" "$dest_dir/$dir/" || { echo -e "${RED}Failed to copy $dir from $SOURCE_DIR to $dest_dir.${NC}"; exit 1; }
        else
            echo -e "${YELLOW}Skipping: $dir does not exist in $SOURCE_DIR.${NC}"
        fi
    done
done

cd "$BASE_DEST"

# init a new git repository if it doesn't exist
if [ ! -d ".git" ]; then
    git init || { echo -e "${RED}Failed to initialize git repository.${NC}"; exit 1; }
fi

# check if a remote named 'origin' exists
if ! git remote get-url origin >/dev/null 2>&1; then
    echo -e "${RED}No remote 'origin' found. Creating a new GitHub repository...${NC}"

    gh repo create "${repo_name}" --private || { echo -e "${RED}Failed to create GitHub repository.${NC}"; exit 1; }
    git remote add origin "git@github.com:$github_username/${repo_name}.git" || { echo -e "${RED}Failed to add remote repository.${NC}"; exit 1; }

    echo -e "${GREEN}Remote 'origin' added successfully.${NC}"
fi

git add . || { echo -e "${RED}Failed to add files to git.${NC}"; exit 1; }

if ! git diff --cached --quiet; then
    git commit -m "automated commit" || { echo -e "${RED}Failed to commit changes.${NC}"; exit 1; }
else
    echo -e "${YELLOW}No changes to commit.${NC}"
fi

# check if 'main' branch exists, if not create it
if ! git branch --list | grep -q 'main'; then
    git branch -m main  # Rename the current branch to main
fi

git push -u origin main --force --prune || { echo -e "${RED}Failed to push changes to remote repository.${NC}"; exit 1; }

echo -e "${GREEN}Backed up successfully!${NC}"
