#!/bin/bash

TODO_GEN_FILE=~/Misc/todo-gen.txt
TODO_CS_FILE=~/Misc/todo-cs.txt

mkdir -p ~/Misc

case "$1" in
  "gen")
    nvim "$TODO_GEN_FILE"
    ;;
  "cs")
    nvim "$TODO_CS_FILE"
    ;;
  *)
    echo "Usage: todo gen | todo cs"
    ;;
esac
